//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoulleteApi.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoulleteApi.Common.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided value is invalid for current operation.
        /// </summary>
        public static string ProvidedValueIsInvalidForCurrentOperation {
            get {
                return ResourceManager.GetString("ProvidedValueIsInvalidForCurrentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too large to add balance.
        /// </summary>
        public static string ValueIsTooLargeToAddBalance {
            get {
                return ResourceManager.GetString("ValueIsTooLargeToAddBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too too large to add jackpot.
        /// </summary>
        public static string ValueIsTooLargeToAddJackpot {
            get {
                return ResourceManager.GetString("ValueIsTooLargeToAddJackpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too too large to bet.
        /// </summary>
        public static string ValueIsTooLargeToBet {
            get {
                return ResourceManager.GetString("ValueIsTooLargeToBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too large to convert.
        /// </summary>
        public static string ValueIsTooLargeToConvert {
            get {
                return ResourceManager.GetString("ValueIsTooLargeToConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too large to subtract from balance.
        /// </summary>
        public static string ValueIsTooLargeToSubtractBalance {
            get {
                return ResourceManager.GetString("ValueIsTooLargeToSubtractBalance", resourceCulture);
            }
        }
    }
}
